#!/bin/bash

g++ -std=c++11 -c -g CountDownLatch.cpp
g++ -std=c++11 -c -g Example1.cpp
g++ -std=c++11 -c -g Example2.cpp
g++ -std=c++11 Example1.o CountDownLatch.o -o Example1.out -lpthread
g++ -std=c++11 Example2.o CountDownLatch.o -o Example2.out -lpthread
rm -f *.o

