#!/bin/bash

# First build the CountDownLatch Library.
g++ -std=c++17 -c -g -fPIC CountDownLatch.cpp
g++ -std=c++17 -fPIC -shared CountDownLatch.o -o libCountDownLatch.so

linkerLibs="-L. -lCountDownLatch -lpthread"

for exampleItem in $(ls Example*.cpp)
do
	g++ -std=c++17 -g $exampleItem $linkerLibs -o ${exampleItem%.cpp}.out
done
rm -f *.o

